apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-platform.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.mariadb.enabled .Values.mariadbIsAlive.enabled }}
        - name: mariadb-isalive
          image: "{{ .Values.mariadbIsAlive.image.repository }}:{{ .Values.mariadbIsAlive.image.tag }}"
          imagePullPolicy: {{ .Values.mariadbIsAlive.image.pullPolicy }}
          env:
            - name: MARIADB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mariadb.auth.existingSecret }}{{ .Values.mariadb.auth.existingSecret }}{{ else }}{{ include "api-platform.fullname" . }}-mariadb{{ end }}
                  key: mariadb-password
          command:
            - "sh"
            - "-c"
            - {{ printf "until mariadb --host=%s-mariadb --user=${MARIADB_USER} --password=${MARIADB_PASSWORD} --execute=\"SELECT 1;\"; do echo waiting for mariadb; sleep 2; done;" .Release.Name }}
        {{- end }}
        {{- if .Values.persistence.sqlite.enabled }}
        - name: set-sqlite-owner
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/www/sqlite"]
          volumeMounts:
            - name: sqlite-storage
              mountPath: /var/www/sqlite
        {{- end }}
        {{- if .Values.importDatabase.enabled }}
        - name: import-database
          image: "{{ .Values.importDatabase.image.repository }}:{{ .Values.importDatabase.image.tag }}"
          imagePullPolicy: "{{ .Values.importDatabase.image.pullPolicy }}"
          env:
            - name: MARIADB_USER
              value: "{{ .Values.mariadb.auth.username }}"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{- if .Values.mariadb.auth.existingSecret -}}{{ .Values.mariadb.auth.existingSecret }}{{- else -}}{{ include "api-platform.fullname" . }}-mariadb{{- end }}"
                  key: mariadb-password
            - name: MARIADB_SOURCE_HOST
              value: "{{ .Values.importDatabase.sourceHost }}"
            - name: MARIADB_DATABASE
              value: "{{ .Values.mariadb.auth.database }}"
          command:
            - "sh"
            - "-c"
            - |
              TABLE_COUNT=$(mariadb --host={{ .Release.Name }}-mariadb --user=${MARIADB_USER} --password=${MARIADB_PASSWORD} --database=${MARIADB_DATABASE} --execute="SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${MARIADB_DATABASE}';" | tail -n 1)
              
              if [ "$TABLE_COUNT" -eq 0 ]; then
                echo "No existing entries found. Importing database..."
                mariadb --host="${MARIADB_SOURCE_HOST}" --user="${MARIADB_USER}" --password="${MARIADB_PASSWORD}" --database="${MARIADB_DATABASE}" > /tmp/dump.sql
                mariadb --host="{{ .Release.Name }}-mariadb" --user="${MARIADB_USER}" --password="${MARIADB_PASSWORD}" --database="${MARIADB_DATABASE}" < /tmp/dump.sql
              else
                echo "Existing database entries found. Skipping import."
              fi
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-platform.fullname" . }}-app
                  key: app-secret
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-platform.fullname" . }}-app
                  key: jwt-passphrase
            {{- if .Values.mariadb.enabled }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mariadb.auth.existingSecret }}{{ .Values.mariadb.auth.existingSecret }}{{ else }}{{ include "api-platform.fullname" . }}-mariadb{{ end }}
                  key: mariadb-password
            - name: DATABASE_URL
              value: "mysql://{{ .Values.mariadb.auth.username }}:$(MARIADB_PASSWORD)@{{ include "api-platform.fullname" . }}-mariadb:3306/{{ .Values.mariadb.auth.database }}"
            {{- end }}
            - name: CORS_ALLOW_ORIGIN
              value: "*"
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
           {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: php-ini-config
              mountPath: /usr/local/etc/php/conf.d/php.ini
              subPath: php.ini
            - name: jwt-keys
              mountPath: /var/www/config/jwt
              readOnly: true
            - name: sqlite-storage
              mountPath: /var/www/sqlite
      volumes:
        - name: php-ini-config
          configMap:
            name: {{ include "api-platform.fullname" . }}-php-ini-config
        - name: jwt-keys
          secret:
            secretName: {{ include "api-platform.fullname" . }}-jwt-keys
        {{- if .Values.persistence.sqlite.enabled }}
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ include "api-platform.fullname" . }}-sqlite
        {{- else }}
        - name: sqlite-storage
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
