apiVersion: batch/v1
kind: Job
metadata:
  name: jwt-key-generator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      # serviceAccountName: secret-manager
      restartPolicy: OnFailure
      containers:
        - name: keygen
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              if kubectl get secret jwt-keys -n {{ .Release.Namespace }} > /dev/null 2>&1; then
                echo "Secret jwt-keys already exists. Skipping."
                exit 0
              fi
              echo "Creating new JWT key pair..."
      
              # Use /tmp for writing keys
              openssl genpkey -algorithm RSA -out /tmp/private.pem -pkeyopt rsa_keygen_bits:2048
              openssl rsa -pubout -in /tmp/private.pem -out /tmp/public.pem
      
              # Create the secret
              kubectl create secret generic jwt-keys \
                --from-file=/tmp/private.pem --from-file=/tmp/public.pem \
                -n {{ .Release.Namespace }}
      
              echo "Secret jwt-keys created successfully."