apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "api-platform.fullname" . }}-secrets-generator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      # serviceAccountName: secret-manager
      restartPolicy: OnFailure
      containers:
        - name: secrets-generator
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              if kubectl get secret {{ include "api-platform.fullname" . }}-jwt-keys -n {{ .Release.Namespace }} > /dev/null 2>&1; then
                echo "Secret jwt-keys already exists. Skipping."
              else
                echo "Creating new JWT key pair..."
                openssl genpkey -algorithm RSA -out /tmp/private.pem -pkeyopt rsa_keygen_bits:2048
                openssl rsa -pubout -in /tmp/private.pem -out /tmp/public.pem
                kubectl create secret generic {{ include "api-platform.fullname" . }}-jwt-keys \
                  --from-file=/tmp/private.pem --from-file=/tmp/public.pem \
                  -n {{ .Release.Namespace }}
                echo "Secret {{ include "api-platform.fullname" . }}-jwt-keys created successfully."
              fi

              if kubectl get secret {{ include "api-platform.fullname" . }}-app -n {{ .Release.Namespace }} > /dev/null 2>&1; then
                echo "Secret app already exists. Skipping."
              else
                echo "Creating new app secrets..."
                JWT_PASSPHRASE=$(openssl rand -base64 32)
                APP_SECRET=$(openssl rand -base64 32)
                kubectl create secret generic {{ include "api-platform.fullname" . }}-app \
                  --from-literal=jwt-passphrase=$JWT_PASSPHRASE --from-literal=app-secret=$APP_SECRET \
                  -n {{ .Release.Namespace }}
                echo "Secret {{ include "api-platform.fullname" . }}-app created successfully."
              fi