apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-platform.fullname" . }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: wait-for-{{ include "api-platform.fullname" . }}
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "api-platform.fullname" . }} 9000; do echo waiting for {{ include "api-platform.fullname" . }}; sleep 2; done;
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: public-files
              mountPath: /var/www/public
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "api-platform.fullname" . }}-nginx-config
        - name: public-files
          emptyDir: {}

