apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-platform.fullname" . }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-{{ include "api-platform.fullname" . }}
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "api-platform.fullname" . }} 9000; do echo waiting for {{ include "api-platform.fullname" . }}; sleep 2; done;
        - name: copy-public-files
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh", "-c", "mkdir -p /usr/share/nginx/html/bundles && cp -r /var/www/public/bundles/* /usr/share/nginx/html/bundles/"]
          volumeMounts:
            - name: public-files
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: public-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "api-platform.fullname" . }}-nginx-config
        - name: public-files
          emptyDir: {}

