{{- if and .Values.secrets.jwtPassphrase .Values.secrets.appSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}-app
type: Opaque
data:
  jwt-passphrase: {{ .Values.secrets.jwtPassphrase | b64enc | quote }}
  app-secret: {{ .Values.secrets.appSecret | b64enc | quote }}
{{- end }}
