apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-passphrase: {{ .Values.secrets.jwtPassphrase | default (randAlphaNum 32 | b64enc) | b64enc }}
  app-secret: {{ .Values.secrets.appSecret | default (randAlphaNum 32 | b64enc) | b64enc }}