{{- $appSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-app" (include "api-platform.fullname" .)) }}
{{- if not $appSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}-app
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-passphrase: {{ .Values.secrets.jwtPassphrase | default (randAlphaNum 32 | b64enc) | quote }}
  app-secret: {{ .Values.secrets.appSecret | default (randAlphaNum 32 | b64enc) | quote }}
{{- end }}

{{- if .Values.mysql.enabled }}
{{- $mysqlSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-mysql" (include "api-platform.fullname" .)) }}
{{- if not $mysqlSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}-mysql
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | default (randAlphaNum 32 | b64enc) | quote }}
  mysql-password: {{ .Values.mysql.auth.password | default (randAlphaNum 32 | b64enc) | quote }}
{{- end }}
{{- end }}