{{- if .Values.customAppConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-app-config-map
data:
{{- range $key, $value := .Values.customAppConfigMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}