apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panorama-server.fullname" . }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: wait-for-{{ .Chart.Name }}
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ include "panorama-server.fullname" . }} {{ .Values.service.port }}; do echo waiting for {{ include "panorama-server.fullname" . }}:{{ .Values.service.port }}; sleep 5; done;']
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "panorama-server.fullname" . }}-nginx-config

