name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish-charts:
    permissions: write-all
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.1

      # - name: Import GPG Key
      #   run: |
      #     echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
      #     gpg --export-secret-keys >~/.gnupg/secring.gpg
      #   env:
      #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Package and Check Charts
        run: |
          which yq || apt-get install yq -y
          git checkout gh-pages
          # Fetch existing charts information
          helm repo index . --merge index.yaml
          git checkout main -- charts
          cd charts
          for dir in */ ; do
            chart_name=$(basename "$dir")
            chart_version=$(cat "$dir/Chart.yaml" | yq e '.version' -)
            if grep -q "$chart_name-$chart_version" ../index.yaml; then
              echo "Chart $chart_name version $chart_version already exists, skipping."
            else
              echo "Packaging new or updated chart $chart_name version $chart_version."
              cd "$dir"
              helm dependency update
              cd ..
              helm package "$dir" -d ..
            fi
          done
          cd ..
          rm -r charts


      - name: Copy Artifact Hub and README files
        run: |
          git checkout gh-pages
          git checkout main -- index.html README.md .gitignore

      - name: Publish Charts to GitHub Pages
        run: |
          helm repo index --url https://f3k-tech.github.io/helm-f3k/ .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Publish Helm charts and additional files"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

